### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by WXBaiHu** [tiangolo/uwsgi-nginx-flask-docker#158]
Hi, I'm trying to get set up with my first flask application, but I'm having issues with deployment. I have a file named startApp.py that imports my flask app from the main file. My flask app is named server. When I have the line "server.run(host='0.0.0.0')" inside of my startApp.py, it runs perfectly and I can access the page from "address:56733". But if I remove that line from the startApp.py, I get ERR_CONNECTION_REFUSED when going to that same url. Any idea of what the problem might be? 

docker-compose.yml
```
version: "3.7"
services:
  web:
    build: ./app
    container_name: flask
    restart: always
    ports:
      - "56733:5000"
```
startApp.py
```
from server import server

#server.run(host='0.0.0.0')
```
Dockerfile
```
FROM tiangolo/uwsgi-nginx-flask:python3.7

COPY . /app

RUN pip install -r requirements.txt

```
uwsgi.ini
```
[uwsgi]
module = startApp
callable = server
master = true

```
