### ISSUE TITLE
Running example flask package with docker-compose throws error

### ISSUE THREAD

**Issue by KingDarBoja** [tiangolo/uwsgi-nginx-flask-docker#160]
Hello!

I am trying to run the provided sample flask package by using **docker-compose** commands instead of **docker build** ones so I don't have to manually stop the container, build it and run for every change on development stage.

However, after running:
`docker-compose build --no-cache && docker-compose up`

The app is properly built and served on http://0.0.0.0:80/ but when I try to navigate into that, I get the following error message:
`flask.cli.NoAppException: Could not import "main".`

![NoAppException](https://user-images.githubusercontent.com/30560560/70279869-51483f80-1785-11ea-9cd7-d492fe71fd58.png)

I haven't changed anything on the sample files besides:
**1.  Adding a config file**

```py
# pylint: disable=too-few-public-methods
"""Configure our Flask enviroment variables in a Pythonic way."""

class Config():
    """Base config class to store and share enviroment variables"""
    DEBUG = False
    TESTING = False

    DB_NAME = "prod-db"
    DB_USERNAME = "root"
    DB_PASSWORD = "example"

class ProductionConfig(Config):
    """Production config class

    Arguments:
        Config {type} -- Config enviroment variables for prod mode.
    """

class DevelopmentConfig(Config):
    """Development config class

    Arguments:
        Config {type} -- Config enviroment variables for dev mode.
    """
    DEBUG = True

    DB_NAME = "dev-db"

class TestingConfig(Config):
    """Testing config class

    Arguments:
        Config {type} -- Config enviroment variables for testing purposes.
    """
    TESTING = True

    DB_NAME = "dev-db"
```

This config file is imported on `app_setup,py` file in order to set enviroment variables:
```py
from ..main import app
from ..api import api
from ..config import ProductionConfig, DevelopmentConfig, TestingConfig

# Load default config values based on enviroment
if app.config["ENV"] == "production":
    app.config.from_object(DevelopmentConfig())
elif app.config["ENV"] == "testing":
    app.config.from_object(TestingConfig())
else:
    app.config.from_object(ProductionConfig())


@app.route("/")
def hello():
    print(f'App config values: {app.config}')
    # This could also be returning an index.html
    return '''Hello World from Flask in a uWSGI Nginx Docker container with \
     Python 3.7 (from the example template), 
     try also: <a href="/users/">/users/</a>'''

```

**2. Replace FLASK_DEBUG by FLASK_ENV on `docker-compose.override.yml`**
```yml
version: '3'
services:
  web:
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=development
      # - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
```

The app loads fine if I use the docker build commands.

If any extra info is need, please reply and I will provide it :)
