### ISSUE TITLE
Running with a prestart.sh script?

### ISSUE THREAD

**Issue by DanielHHowell** [tiangolo/uwsgi-nginx-flask-docker#208]
Amazing work tiangolo!

I've had great success with this for multiple projects - now I am having some difficulty getting it work with a more complex project that requires some db initializations. In the Dockerfile you mention the ability to simply include a `prestart.sh` in the `/app` folder, but can't seem to get Docker to recognize this. Any other pointers?

**Comment by tpoerschke** [comment]
Hi :)

I encountered the same issue. It turns out that the `docker-compose.overrides.yml` ist the reason for this (in my case). But I was able to fix it, just modified the "command" entry in the `docker-compose.overrides.yml`:

```
command: bash -c 'bash prestart.sh && flask run --host=0.0.0.0 --port=80'
```

My `docker-compose.overrides.yml` looks something like this:
```
version: '3'
services:
  web:
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: bash -c 'bash prestart.sh && flask run --host=0.0.0.0 --port=80'
```

_Note_: Building the image and running it directly, executes the prestart.sh (in my case).

I hope I was able to help you :)
