### ISSUE TITLE
Do I still need supervisor if I use this setup?

### ISSUE THREAD

**Issue by rlam3** [tiangolo/uwsgi-nginx-flask-docker#31]
Do I still need supervisor if I use this setuup?

**Comment by tiangolo** [comment]
Behind the scenes, this uses Supervisor to control Nginx and uWSGI.

And if you want to make sure your Docker container re-starts in case of failure, you should use [`--restart always`](https://docs.docker.com/engine/admin/start-containers-automatically/).

What else do you think you could need supervisor for?

**Comment by rlam3** [comment]
I was thinking of using supervisor for my celery workers and keeping elastic search engine alive.. Was wondering what your thoughts are on this. Thanks!

**Comment by tiangolo** [comment]
Ah, I see. I think you might want to check this out: https://github.com/senseta-os/senseta-base-project

It's based on this same image and it includes a DB, some basic SQLAlchemy models, Celery worker, RabbitMQ, etc.

You could put an elastic search service in the same way as the database (we use it quite frequently). Check out the official ES guide: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

You could use something like this:

```
elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.6.0'
    volumes:
      - 'elasticsearch-data:/usr/share/elasticsearch/data'
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - cluster.name=docker-cluster
      # # This generated errors
      # - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
```
