### ISSUE TITLE
Connect postgres(psycopg2) with the main.py

### ISSUE THREAD

**Issue by anubhav3itb** [tiangolo/uwsgi-nginx-flask-docker#46]
I tried to connect postgres db from main.py, but its giving `OperationalError: received invalid response to SSL negotiation: H`. This issue is because the port 5432 is not properly exposed.

DOCKERFILE
```
FROM tiangolo/uwsgi-nginx-flask:python2.7
ENV LISTEN_PORT 5432
EXPOSE 5432
COPY tmp.conf /etc/nginx/conf.d/tmp.conf
COPY ./app /app
RUN pip install -r /app/requirements.txt
``` 
main.py
```
from flask import Flask
import psycopg2
app = Flask(__name__)

@app.route("/")
def hello():
    db = psycopg2.connect(host='127.0.0.1', port=5432, user='postgres',
                          password='123', dbname='chatbotdev')
    return "Hello World from Flask"

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=80)
```

tmp.conf
```
server {
    listen 8080 default_server;
    listen [::]:8080 default_server;

    location / {
      try_files $uri @app;
    }

    location @app {
        include uwsgi_params;
        uwsgi_pass unix:/tmp/uwsgi.sock;
    }
}
```
requirements.txt
`psycopg2==2.7.3.1`

Can someone please explain, how can I use postgres within this docker container, because I'm able to do this in other linux docker containers.

**Comment by egimbernat** [comment]
Where is postgree? Is another container?
You are exposing the postgree default port (5432) on your web (Flask application) container, also, in your nginx conf the given port is 8080, and on your main.py the 80.

You need to:

- [ ] Configure the desired port for the Flask Application/Web Container, this is, use only one port. The 80 is to classic and there is a chance that collide with other operations. You can use 8080.
- [ ] Select you prefered docker technology, you have two options, manually create docker containers for Postgres and Flask Application and link it with a network or use docker-compose like below snnipet.

`postgresql:
    container_name: postgresql
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=<CHANGE>
      - POSTGRES_USER=<CHANGE>
      - POSTGRES_PASSWORD=test
      - POSTGRES_ROOT_PASSWORD=test
    restart: always

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      - VIRTUAL_HOST=auth.test.org
      - VIRTUAL_PORT=8080
      - POSTGRES_PASSWORD=test
      - POSTGRES_PORT_5432_TCP_ADDR=postgresql
      - POSTGRES_PORT_5432_TCP_PORT=5432
    restart: always

volumes:
  postgres_data: {}`

**Comment by anubhav3itb** [comment]
Hi @egimbernat,

I tried your method i.e using different containers, but I'm still getting errors while calling the postgres port (5432) from main.py file.
```
OperationalError: could not connect to server: Connection refused
web           | 	Is the server running on host "127.0.0.1" and accepting
web           | 	TCP/IP connections on port 5432?
```

docker-compose.yml
```
version: '2.1'
services:
  postgresql:
    container_name: postgresql
    image: postgres:10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatbotdev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_ROOT_PASSWORD=123
    restart: always

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_PORT_5432_TCP_ADDR=postgresql
      - POSTGRES_PORT_5432_TCP_PORT=5432
    restart: always

volumes:
  postgres_data: {}
```
main.py
```
from flask import Flask
import psycopg2
app = Flask(__name__)

@app.route("/")
def hello():
    db = psycopg2.connect(host='localhost', port=5432, user='postgres',
                              password='123', dbname='chatbotdev')
    return "Hello World from Flask"

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=80)

```
Dockerfile
```
FROM tiangolo/uwsgi-nginx-flask:python2.7
COPY tmp.conf /etc/nginx/conf.d/tmp.conf
COPY ./app /app
RUN pip install -r /app/requirements.txt
```
The rest of the files are same. Can you please help me out as I'm still new to this.
