### ISSUE TITLE
docker-compose doesn't watch the changes.

### ISSUE THREAD

**Issue by bebignet** [tiangolo/uwsgi-nginx-flask-docker#64]
I'm new with docker.
i am using own image and use tiangolo/uwsgi-nginx:python3.6-alpine3.7 image. it runs well.
Here is my docker-compose.yml
```
version: '3'
services:
  image: "cmbot:latest"
  web:
    build: ./
    ports:
     - "5000:80"
    volumes:
      - ./app:/app
```
but when I change the code it is not watched or copied to the container. 
Any advice ? Thank you.

**Comment by tiangolo** [comment]
Start with the Docker quickstart: https://docs.docker.com/get-started/

Then everything should be a bit more clear.

---

Then, in your local environment you are mounting your app code as a volume, it is not copied, but is "mounted", that means that it's actually the same code, the same directory, is not a "watch" program that copies it, it should be the same code and directory.

If you deploy it somehow, you have to first build it, mounting the app volume only works as a trick during development.

Your `image: "cmbot:latest"` is outside the `web` service, it should be inside of it.

**Comment by bebignet** [comment]
```
version: '3'
services:
  web:
    image: "cmbot:latest"
    build: ./
    ports:
     - "5000:80"
    volumes:
      - ./app:/app
```
Sorry, wrong paste. I have read the quickstart, thank you for your advice.
##
"volumes" in the docker-compose, If it is the mounted directory to the container, it should be sync with the directory where i develop, right?

I have built php app image and with "volumes" alone and it is worked when i change something on my side, the container also changed.

But with this flask image, i should do "docker-compose up" everytime i change the code. 
##
anyway thank you for your answer. I will read more about the build.
