### ISSUE TITLE
Container runs Python 2.7 instead of Python 3.6

### ISSUE THREAD

**Issue by pymooner** [tiangolo/uwsgi-nginx-flask-docker#86]
i have an app structured as follow:
```
app
    app
       main.py
    Dockerfile
    uwsgi.ini
docker-compose.yml
```
Dockerfile:
```
FROM tiangolo/uwsgi-nginx-flask:python3.6
RUN pip3 install gensim pymongo pandas numpy
```

docker-compose.yml:
```
version: '2'
services:
  s_a:
    build: ./app
    links:
      - s_db
    volumes:
      - ./app/app:/app
    ports:
      - "8080:80"
    
  s_db:
    image: mongo
    ports:
      - "27370:27017"
    volumes:
      - ./app/mongodb:/data/db
```
uwsgi.ini:
```
[uwsgi]
module = app.main
callable = app

master = true
processes = 10
```

when up `docker-compose.yml` i get the error:
![error](https://user-images.githubusercontent.com/39664907/46013749-00957b00-c0da-11e8-970d-25a7303696c7.png)

I don't know why the runs on Python 2.7 instead of Python 3.6.
Where is the problem ?
